<?php
# This file was automatically generated by the MediaWiki 1.45.3
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "EverQuest Legends Wiki";
$wgMetaNamespace = "EQLWiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://eqlwiki.com";
$wgCanonicalServer = "https://eqlwiki.com";

# Share MediaWiki login cookies across eqlwiki.com and www.eqlwiki.com.
$wgCookieDomain = ".eqlwiki.com";
$wgCookiePath = "/";
$wgCookieSecure = true;
$wgCookieSameSite = "Lax";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/EQL_Wiki_Logo_Blue_135x135.png",
	'icon' => "$wgResourceBasePath/resources/assets/EQL_Wiki_Logo_Blue_135x135.png",
];

$wgFavicon = "/favicon.ico";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "veronicamori@live.com";
$wgPasswordSender = "admin@eqlwiki.com";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "eqlwikdq_mw14188";
$wgDBuser = "eqlwikdq_mw14188";
$wgDBpassword = 'CHANGE_ME';

# MySQL specific settings
$wgDBprefix = "mw_";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "America/New_York";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = 'CHANGE_ME';

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = 'CHANGE_ME';

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = 'CHANGE_ME';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin.
## EQLImmersive is the default for anonymous users and new accounts.
$wgDefaultSkin = "eqlimmersive";

# Enabled skins.
# Keep EQLImmersive and Vector loaded.
# Vector provides both legacy Vector ('vector') and Vector 2022 ('vector-2022').
wfLoadSkin( 'EQLImmersive' );
wfLoadSkin( 'Vector' );

# Hide legacy Vector from user skin preferences.
# This leaves only EQLImmersive and Vector 2022 selectable.
$wgSkipSkins = $wgSkipSkins ?? [];
$wgSkipSkins[] = 'vector';

# Prefer this order in user preferences.
$wgSkinsPreferred = [
	'eqlimmersive',
	'vector-2022'
];

# Vector 2022 defaults.
# Keep Vector available, but make its sidebars/panels collapsed by default.
$wgDefaultUserOptions['vector-limited-width'] = 0;
$wgDefaultUserOptions['vector-main-menu-pinned'] = 0;
$wgDefaultUserOptions['vector-toc-pinned'] = 0;
$wgDefaultUserOptions['vector-page-tools-pinned'] = 0;
$wgDefaultUserOptions['vector-appearance-pinned'] = 0;

# Legacy / compatibility sidebar defaults for Vector builds that support them.
$wgVectorDefaultSidebarVisibleForAnonymousUser = false;
$wgVectorDefaultSidebarVisibleForAuthorisedUser = false;



# End of automatically generated settings.
# Add more configuration options below.

$wgTmpDirectory = "/home/eqlwikdq/tmp_aqjv2b";

# Security setup
$wgAccountCreationThrottle = [ [
    'count' => 10,
    'seconds' => 86400,
] ];

$wgPasswordAttemptThrottle = [
	// Short term limit.
	[ 'count' => 5, 'seconds' => 300 ],
	// Long term limit.
	// We need to balance the risk of somebody using this as a DoS attack to lock someone out of their account, and someone doing a brute force attack.
	[ 'count' => 150, 'seconds' => 60 * 60 * 48 ],
];

# Security extensions

wfLoadExtensions([ 'ConfirmEdit', 'ConfirmEdit/Turnstile' ]);
$wgCaptchaClass = MediaWiki\Extension\ConfirmEdit\Turnstile\Turnstile::class;
$wgTurnstileSiteKey= '0x4AAAAAACxQBUF9Y3AqzhAb';
$wgTurnstileSecretKey= 'CHANGE_ME';
$wgCaptchaTriggers['create'] = false;
$wgCaptchaTriggers['sendemail'] = false;

$wgEmailConfirmToEdit = true;

# Max upload size
$wgMaxUploadSize = 134217728;

# Short URL
$wgArticlePath = "/$1";
$wgUsePathInfo = true;

# Interwiki permissions
$wgGroupPermissions['sysop']['interwiki'] = true;

# ------------------------------------
# Custom Namespaces (Magelo characters)
# ------------------------------------
define("NS_MAGELO_BLUE", 500);
define("NS_MAGELO_BLUE_TALK", 501);
define("NS_MAGELO_RED", 502);
define("NS_MAGELO_RED_TALK", 503);

$wgExtraNamespaces[NS_MAGELO_BLUE]      = "Magelo_Blue";
$wgExtraNamespaces[NS_MAGELO_BLUE_TALK] = "Magelo_Blue_talk";
$wgExtraNamespaces[NS_MAGELO_RED]       = "Magelo_Red";
$wgExtraNamespaces[NS_MAGELO_RED_TALK]  = "Magelo_Red_talk";
$wgNamespacesToBeSearchedDefault = [ NS_MAIN => true, NS_MAGELO_BLUE => true, NS_MAGELO_RED => true ];

# ------------------------------------
# Extensions
# ------------------------------------
require_once( "$IP/extensions/ClassSlotEquip/ClassSlotEquip.php" );
require_once( "$IP/extensions/AjaxHoverHelper/AjaxHoverHelper.php" );
require_once( "$IP/extensions/DynamicZoneList/DynamicZoneList.php" );
require_once( "$IP/extensions/DynamicQuestItemList/DynamicQuestItemList.php");

# Allow the wiki to serve/display its own auction chart images
$wgAllowExternalImagesFrom = 'https://eqlwiki.com/';

wfLoadExtension( 'ParserFunctions' );
$wgPFEnableStringFunctions = true;

wfLoadExtension( 'CategoryTree' );

wfLoadExtension( 'Variables' );
wfLoadExtension( 'Scribunto' );
$wgScribuntoDefaultEngine = 'luastandalone';
$wgExpensiveParserFunctionLimit = 10000;


wfLoadExtension( 'LabeledSectionTransclusion' );
$wgShowExceptionDetails = false;
require_once "$IP/extensions/ItemLevelSlider/ItemLevelSlider.php";

# Cache busting
$wgCacheEpoch = '202605160046';
$wgInvalidateCacheOnLocalSettingsChange = false;
wfLoadExtension( 'VisualEditor' );

// Enable for main namespace (0) and optionally others
$wgVisualEditorAvailableNamespaces = [
    NS_MAIN => true,
];

// Make it the default editor
$wgDefaultUserOptions['visualeditor-enable'] = 1;
$wgDefaultUserOptions['visualeditor-editor'] = 'visualeditor';

// Point to bundled Parsoid
$wgVirtualRestConfig['modules']['parsoid'] = [
    'url' => $wgServer . $wgScriptPath . '/rest.php',
    'domain' => $wgServer,
    'prefix' => $wgDBname,
];

wfLoadExtension( 'ReplaceText' );

// EQL unified logout link.
// Replaces MediaWiki's normal logout URL with our unified wiki+forum logout script.
$wgHooks['SkinTemplateNavigation::Universal'][] = function ( $skinTemplate, &$links ) {
    $logoutUrl = 'https://eqlwiki.com/eql_logout.php';

    // Modern skins, including current Vector-style user menu.
    if ( isset( $links['user-menu']['logout'] ) ) {
        $links['user-menu']['logout']['href'] = $logoutUrl;
    }

    // Some skins/menus may expose logout in user-page or other personal areas.
    if ( isset( $links['user-page']['logout'] ) ) {
        $links['user-page']['logout']['href'] = $logoutUrl;
    }

    // Fallback: scan all top-level menu groups for a logout item.
    foreach ( $links as &$menu ) {
        if ( is_array( $menu ) && isset( $menu['logout'] ) && is_array( $menu['logout'] ) ) {
            $menu['logout']['href'] = $logoutUrl;
        }
    }

    return true;
};

// EQL Wiki 2FA via MediaWiki OATHAuth.
$wgOATHAuthAccountPrefix = 'EQL Wiki';
wfLoadExtension( 'OATHAuth' );

// DynamicPageList Support
// Extension folder: /extensions/intersection
// Provides <DynamicPageList> category-intersection lists.
wfLoadExtension( 'intersection' );

//EQL Zone Viewer
wfLoadExtension( 'EQLZoneViewer' );

// DynamicPageList safety limits.
// Variable names use "DLP" because that is how this extension defines them.
$wgDLPAllowUnlimitedResults = true;
$wgDLPAllowUnlimitedCategories = true;

// Allow normal logged-in users to enable 2FA.
$wgGroupPermissions['user']['oathauth-enable'] = true;

// Allow sysops to help manage 2FA recovery/admin support.
$wgGroupPermissions['sysop']['oathauth-disable-for-user'] = true;
$wgGroupPermissions['sysop']['oathauth-verify-user'] = true;
$wgGroupPermissions['sysop']['oathauth-view-log'] = true;

// Vector 2022 native appearance/dark mode.
$wgVectorNightMode['beta'] = true;
$wgVectorNightMode['logged_out'] = true;
$wgVectorNightMode['logged_in'] = true;

// Default color mode for users/visitors without a saved preference.
// Options: 'day', 'night', or 'os'.
$wgDefaultUserOptions['vector-theme'] = 'day';

// EQL: Create SMF forum account immediately when a wiki account is created.
$wgHooks['LocalUserCreated'][] = function ( $user, $autocreated ) {
    // Skip auto-created accounts (e.g. CentralAuth, imports).
    if ( $autocreated ) {
        return true;
    }

    global $IP;
    require_once "$IP/bb/smf_create_member.php";

    $ip = RequestContext::getMain()->getRequest()->getIP();

    smf_create_shadow_member(
        $user->getName(),
        (string)$user->getEmail(),
        $ip
    );

    return true;
};

// Raise parser expansion ceiling.
// Default is 2048 KiB = 2 MiB.
// 4096 KiB = 4 MiB.
$wgMaxArticleSize = 8192;

// Recommended when raising $wgMaxArticleSize, especially for API parse/lazy-load use.
$wgAPIMaxResultSize = $wgMaxArticleSize * 8192;

// Extension:UserPageEditProtection
wfLoadExtension( 'UserPageEditProtection' );
$wgOnlyUserEditUserPage = true;

# Spell Level Slider

// BEGIN EQLCLIENTDATA STAGED ROLLOUT
// Stage 01: batched, revision-aware era metadata.
wfLoadExtension( 'EQLClientData' );

$wgEQLClientDataEnableEra = true;

// Later stages remain disabled until tested individually.
$wgEQLClientDataEnableVerification = true;
$wgEQLClientDataEnableSpellOverrides = true;
$wgEQLClientDataVerificationModuleName = 'skins.EQLImmersive.verification';
// Cross-tab browser results stay fresh for at most 5 minutes.
$wgEQLClientDataEraStatusClientTtlSeconds = 300;

// One request can cover a large link-heavy page.
$wgEQLClientDataApiMaxTitles = 500;
// END EQLCLIENTDATA STAGED ROLLOUT
require_once "$IP/extensions/SpellLevelSlider/SpellLevelSlider.php";

// Template Edit Protection
$wgNamespaceProtection[NS_TEMPLATE] = array( 'editprotected' );

# ============================================================
# BEGIN EQL PERMANENT CACHE CONFIG
# ============================================================

# Main lightweight/object cache.
# CACHE_ACCEL uses APCu when the PHP extension is installed.
# The existing earlier CACHE_ACCEL setting may remain; this
# explicit block documents the intended production architecture.
$wgMainCacheType = CACHE_DB;

# Sessions must remain durable rather than relying on APCu.
$wgSessionCacheType = CACHE_DB;

# Parser output can be very large. Keep it in MediaWiki's
# persistent database parser cache instead of consuming APCu.
$wgParserCacheType = CACHE_DB;

# Filesystem-backed localisation/cache data outside public_html.
$wgCacheDirectory = '/home/eqlwikdq/private-cache/mediawiki';

# ============================================================
# END EQL PERMANENT CACHE CONFIG
# ============================================================

# Server-side cache for the EQL Icon Finder
// TEMPORARILY DISABLED DURING OUTAGE INVESTIGATION
// // TEMPORARILY DISABLED DURING OUTAGE INVESTIGATION
// wfLoadExtension( 'EQLIconIndex' );

# EQL: MediaWiki jobs run from throttled CLI cron, not web requests.
$wgJobRunRate = 0;


# ============================================================
# EQL_RESOURCELOADER_MAXAGE_30M_V1
#
# Reduce repeated PHP/load.php executions from returning clients.
#
# Versioned resources remain cacheable for 30 days.
# Unversioned ResourceLoader responses increase from the default
# 5 minutes to 30 minutes.
# ============================================================
$wgResourceLoaderMaxage = [
    'versioned'   => 30 * 24 * 60 * 60,
    'unversioned' => 30 * 60,
];

