/* Any changes to this file will be overwritten. To change the content
of this file, edit the source files from which it was compiled. */
function getClosest(el,divID){if(typeof divID=='undefined'||divID==!1)
return null;do{if(el.nodeName==='TEXTAREA'||el.nodeName==='INPUT'||el.id==='error_box')
break;if(el.id===divID){return el}}
while(el=el.parentNode);return null}
function getSelectedText(node){var selection=window.getSelection();for(var i=0;i<selection.rangeCount;i++){const range=selection.getRangeAt(i);if(range.intersectsNode(node)){const
frag=range.cloneContents(),s=getClosest(range.startContainer,node.id),e=getClosest(range.endContainer,node.id);if(s&&e){const container=document.createElement("div");container.appendChild(range.cloneContents());return container.innerHTML}else{const el=frag.getElementById(node.id);return el?.innerHTML}}}}
function quotedTextClick(oOptions){text='';$('#quoteSelected_'+oOptions.msgID).hide();$.ajax({url:smf_prepareScriptUrl(smf_scripturl)+'action=quotefast;quote='+oOptions.msgID+';xml;pb='+oEditorID+';mode='+(oEditorObject?.bRichTextEnabled?1:0),type:'GET',headers:{"X-SMF-AJAX":1},xhrFields:{withCredentials:typeof allow_xhjr_credentials!=="undefined"?allow_xhjr_credentials:!1},dataType:'xml',beforeSend:function(){ajax_indicator(!0)},complete:function(jqXHR,textStatus){ajax_indicator(!1)},success:function(data,textStatus,xhr){oOptions.text=oOptions.text.replaceAll(/<img src=".*?" alt="(.*?)" title=".*?" class="smiley">/,'$1');text=$(data).find('quote').text();text=text.match(/^\[quote(.*)]/ig)+oOptions.text+'[/quote]'+'\n\n';var e=$('#'+oEditorID).get(0);var oEditor=sceditor.instance(e);text=oEditor.toBBCode(text);oEditor.insert(text);if(typeof oJumpAnchor!='undefined'){if(navigator.appName=='Microsoft Internet Explorer')
window.location.hash=oJumpAnchor;else window.location.hash='#'+oJumpAnchor}},error:function(xhr,textStatus,errorThrown){}})}
$(function(){$(document).on('mouseup','.inner, .list_posts',function(){var oSelected={divID:$(this).attr('id'),msgID:$(this).data('msgid'),};const node=this;oSelected.text=getSelectedText(this);if(typeof oSelected.text=='undefined'||oSelected.text==!1)
return!0;$('#quoteSelected_'+oSelected.msgID).show();$(document).off('click','#quoteSelected_'+oSelected.msgID+' a');$(document).one('click','#quoteSelected_'+oSelected.msgID+' a',function(e){e.preventDefault();quotedTextClick(oSelected)});$(document).on('click.ondeselecttext'+oSelected.msgID,function(){setTimeout(function(){selectedText=getSelectedText(node);if(typeof selectedText!='undefined'&&selectedText!=!1)
return;$(document).off('click','#quoteSelected_'+oSelected.msgID+' a');$('#quoteSelected_'+oSelected.msgID).hide();$(document).off('click.ondeselecttext'+oSelected.msgID)},1)});return!0})});var fails=[];var atwhoConfig={at:'@',data:[],show_the_at:!0,startWithSpace:!0,limit:10,callbacks:{remoteFilter:function(query,callback){if(typeof query=='undefined'||query.length<2||query.length>60)
return;for(i in fails)
if(query.substr(0,fails[i].length)==fails[i])
return;$.ajax({url:smf_scripturl+'?action=suggest;'+smf_session_var+'='+smf_session_id+';xml',method:'GET',headers:{"X-SMF-AJAX":1},xhrFields:{withCredentials:typeof allow_xhjr_credentials!=="undefined"?allow_xhjr_credentials:!1},data:{search:query,suggest_type:'member'},success:function(data){var members=$(data).find('smf > items > item');if(members.length==0)
fails[fails.length]=query;var callbackArray=[];$.each(members,function(index,item){callbackArray[callbackArray.length]={name:$(item).text()}});callback(callbackArray)}})},tplEval:function(tpl,map,caller){var error,error1,template;template=tpl;try{if(typeof tpl!=='string'){template=tpl(map)}
if(caller=='onInsert'){map.name=map.name.toString().replace("&#034;",'"').replace('&#39;',"'")}
return template.replace(/\$\{([^\}]*)\}/g,function(tag,key,pos){return map[key]})}catch(error1){error=error1;return""}}}};$(function(){$('textarea[name=message]').atwho(atwhoConfig);$('.sceditor-container').find('textarea').atwho(atwhoConfig);var iframe=$('.sceditor-container').find('iframe')[0];if(typeof iframe!='undefined')
$(iframe.contentDocument.body).atwho(atwhoConfig);})